[project]
name = "deepwiki-to-md"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Shinichi Suwa", email = "suwash01@gmail.com" }
]
dependencies = [
    "playwright>=1.52.0",
    "beautifulsoup4>=4.13.4",
    "lxml>=5.4.0",
    "markdownify>=1.1.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pip>=25.1.1",
    "ruff>=0.11.9",
    "pytest>=8.3.5",
    "pytest-playwright>=0.7.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/deepwiki_to_md"]
