[project]
name = "deepwiki-down"
version = "1.0.0"
description = "Add your description here"
dependencies = [
    "playwright>=1.52.0",
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.30.1",
]
requires-python = ">= 3.11"
