services:
  # 本地构建
  # docker build -f ./docker/deepwiki-down/Dockerfile.CI -t deepwiki-down .
  deepwiki-down:
    image: docker.1ms.run/onlyie/prisma-ai-deepwiki-down:latest
    # image: deepwiki-down
    container_name: deepwiki-down
    volumes:
      # docker run -v 需要处理windows兼容性
      - ../../../project_wikis:/output
    command: wiki https://deepwiki.com/weicanie/prisma-ai -o /output
